# Generated by Django 3.1 on 2020-11-07 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ccas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinCCA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cca_to_student', to='ccas.cca')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('matric_number', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('year', models.PositiveSmallIntegerField(default=1)),
                ('course', models.CharField(max_length=256)),
                ('membership_status', models.CharField(max_length=1)),
                ('ccas', models.ManyToManyField(related_name='students', through='students.JoinCCA', to='ccas.CCA')),
            ],
        ),
        migrations.AddField(
            model_name='joincca',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_to_cca', to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='joincca',
            unique_together={('cca', 'student')},
        ),
    ]
